project:
  type: website

website:
  title: "Cetubone"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
      - href: postNdx.qmd
        text: Blogs

format:
  html:
    theme:
      - cosmo
      - brand
    css: 
      - styles.css
      - custom.css
    toc: true




