project:
  type: website

website:
  title: "Cetubone"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
      - href: postNdx.qmd
        text: Blogs
      - href: https://github.com/Cetubone/cetubone.github.io/issues
        text: Issues
      - href: about.qmd
        text: About

format:
  html:
    theme: cyborg
    css: styles.css
    toc: false
    include-after-body: _include-body.html




