project:
  type: website

website:
  title: "Cetubone"
  navbar:
    left:
      - href: index.qmd
        text: Home
      # - about.qmd
      - href: postNdx.qmd
        text: Blogs

format:
  html:
    theme:
      dark: cyborg
      light: cosmo
    css: styles.css
    toc: true




